### ISSUE TITLE
Determine what values can come back as BQ access roles

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1050]
See #1046

**Comment by dhermes** [comment]
From the original PR:

@fhoffa Is it possible for there to be more than one key in an "access" (ACL) object returned?

The [spec][1] indicates

```json
    {
      "role": "...",
      "userByEmail": "...",
      "groupByEmail": "...",
      "domain": "...",
      "specialGroup": "...",
      "view": {
        "projectId": "...",
        "datasetId": "...",
        "tableId": "..."
      }
    }
```

but empirically @tseaver seems to only be seeing one key and it is always one of `userByEmail`, `groupByEmail` and `specialGroup`.

[1]: https://cloud.google.com/bigquery/docs/reference/v2/datasets

**Comment by dhermes** [comment]
@jgeewax Is there someone who works on BigQuery we can reach out to?

**Comment by fhoffa** [comment]
bumping internally!

**Comment by dhermes** [comment]
Thanks @fhoffa!

**Comment by jcondit** [comment]
BQ engineer here. Every entry in the access list will have exactly one of userByEmail, groupByEmail, domain, specialGroup, or view set. And if anything but view is set, it'll also have a role specified (role is omitted for a view, since views are always read-only, though arguably we should be setting it anyway).

This is documented somewhat obliquely by the "[Pick one]" prefix in the field descriptions here:
https://cloud.google.com/bigquery/docs/reference/v2/datasets

**Comment by dhermes** [comment]
Thanks @jcondit!

**Comment by dhermes** [comment]
@jcondit Thanks I finally got the fix out. It seems

https://cloud.google.com/bigquery/access-control#datasetroles

could be updated to be more in line with

https://cloud.google.com/bigquery/docs/reference/v2/datasets

Cheers!
