### ISSUE TITLE
Do we need an 'ndb'-like ORM for BQ table schema?

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1058]
From: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1047#discussion_r36790058

@jgeewax WDYT?

**Comment by jgeewax** [comment]
OK I'm legit scared of the idea, however I can completely understand the usefulness of something like this.

Is there no way we can write an adapter for an existing SQL-ORM-like project (ie, [SQL Alchemy](http://www.sqlalchemy.org/)) so that you can use SQL Alchemy to define a schema and talk to BigQuery?

**Comment by jgeewax** [comment]
Just added a note, the node guys are seeing a similar problem (https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/217)

**Comment by dhermes** [comment]
Node or Ruby?

**Comment by jgeewax** [comment]
Whoops sorry, brain fart. Ruby.

**Comment by dhermes** [comment]
@jgeewax We are a good chunk of the way there with `bigquery.table.SchemaField`.

@tseaver Re-open if you think we could do better.
