### ISSUE TITLE
Failing build?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1444]
Looks like the build is failing? Any thoughts @dhermes @tseaver ?

**Comment by dhermes** [comment]
The last merge to master [failed][1] due to flaky-ness of the system tests. I used to manually restart builds so we'd have green but then we lose the history of what failures occurred so I stopped doing it.

Tracking this phenomenon in #1391.

[1]: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/105919343
