### ISSUE TITLE
Cannot reload BigQuery job status or results in sync queries

### ISSUE THREAD

**Issue by ernestoalejo** [GoogleCloudPlatform/gcloud-python#1551]
- The documentation [here](https://googlecloudplatform.github.io/gcloud-python/latest/bigquery-usage.html#querying-data-synchronous) is not valid as it uses an undeclared variable (`job`) and a function that doesn't exist in sync queries (`query.reload()`).
 - When I tried to use `query.job` I found each time it returns a different job instance, which is confusing.
 - After caching `job = query.job` in a variable I was able to use `job.state != 'DONE'` and `job.reload()` to keep track of the job status instead of `query.completed` like documented (literally `job.completed`); but I had to call `query.fetch_data()` to manually extract the rows from the query. This makes the `Query` class a simple factory method to build new jobs.

I'm not sure if this is only a documentation issue or if the `QueryJob` class lacks some important methods to be more than a factory for new jobs.

**Original code in the documentation:**
```python
    query = """
      SELECT count(*) AS age_count FROM dataset_name.person_ages
    """
    query = client.run_sync_query(query)
    query.timeout_ms = 1000
    query.run()  # API request
    retry_count = 100
    while retry_count > 0 and not job.complete:
      retry_count -= 1
      time.sleep(10)
      query.reload()  # API request
    print query.rows
```

**Modified code:**
```python
    q = """
      SELECT count(*) AS age_count FROM dataset_name.person_ages
    """
    query = client.run_sync_query(q)
    query.timeout_ms = 1000
    query.run()  # API request

    job = query.job

    retry_count = 100
    while retry_count > 0 and not job.state != 'DONE':
      retry_count -= 1
      time.sleep(10)
      job.reload()  # API request

    (rows, _, _) = query.fetch_data()
    print rows
```

**Comment by tseaver** [comment]
Thanks for the report!  I am working on cleaning up the example to address your issues.

The intent for the "synchronous" query is to make it easy to handle "simple" queries which run in bounded time.  In that case, `query.complete` will be `True` after `query.run()`, and the first batch (or only batch, if the result is small enough) will be available as `query.rows`.

If the synchronous query times out, then the procedure you discovered (poll the `query.job` until it is finished) is correct.  At that point, you have to use `query.fetch_data` to get even the initial set of rows (because the query doesn't get access to the async results).

> When I tried to use query.job I found each time it returns a different job instance, which is confusing.

Given the expected usecase (use the job to poll until a timed-out query is complete), I didn't anticipate needing to ensure that multiple accesses to `query.job` would return the same instance. #1673 tracks this issue.

**Comment by tseaver** [comment]
@ernestoalejo #1674 has the expanded documentation for synchronous query usage.
