### ISSUE TITLE
[Documentation Issue]  Styling Side Bar 

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/gcloud-python#1704]
Page Name: index
Release: 0.12.0
Grey stops showing after one scrolls down a bit in webpage.
![hha0yyaktzz](https://cloud.githubusercontent.com/assets/1738983/14368986/419975f4-fcd6-11e5-94a9-c1abf4c1982a.png)

**Comment by jgeewax** [comment]
Thanks for the heads up @cobookman . We're working on a bigger-picture way to sort this out where we export docs as JSON and then use a shared Angular app (see https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/site)

I'm going to close this out, but not because it's not broken -- only because we're fixing it another way.

Thanks again for filing the issue :)

**Comment by dhermes** [comment]
Yup. We also had #1028 for this but closed it for the same reason.
