### ISSUE TITLE
Do params in class docstrings refer to constructor arguments or public instance attributes?

### ISSUE THREAD

**Issue by rimey** [GoogleCloudPlatform/gcloud-python#1731]
Questions only:
* I have the impression that the `gcloud-python` convention is to document the parameters of `__init__` in the class docstring. Is that correct?
* If that is the case, it would appear that there is no particular convention for documenting public instance attributes, except when they happen to be implemented using `@property`. Also correct?

**Comment by dhermes** [comment]
Constructor arguments. AFAIK this is the Sphinx convention. By default `__init__` doesn't get documented so that is the desired place to document it. That said, it would be nice to have a way to document public attributes.

**Comment by rimey** [comment]
OK, thanks.

**Comment by tseaver** [comment]
If defaults for public attributes are defined at class scope, one can add docstrings immediately following the assignment, and have them show up in Sphinx.  E.g.:

```python
class Foo(object):
    """Class docstring here."""
    bar = None
    """Docstring for :attr:`bar` here."""
```

`gcloud-python` mostly uses this pattern for class-level constants, rather than instance attributes:  we tend not to think of non-property-driven attributes as really public.
