### ISSUE TITLE
happybase emulation docs mention private api

### ISSUE THREAD

**Issue by wbolster** [GoogleCloudPlatform/gcloud-python#1761]
the page at https://googlecloudplatform.github.io/gcloud-python/latest/happybase-package.html mentions `make_row()` and `make_ordered_row()`, both of which are _not_ public api. please don't mention those at all. :)

(fyi: i'm the happybase author)

**Comment by dhermes** [comment]
@wbolster [`happybase.table.make_row`][1] and [`happybase.table.make_ordered_row`][2] are both public in the `happybase.table` module / namespace. I realize they are helpers / not intended for users, but the names don't start with `_`, hence they are public. I'm happy to remove them since [they][3] both just [raise][4] a `NotImplementedError`.

I totally recognized your name, though thanks for the reminder you're the author.

[1]: https://github.com/wbolster/happybase/blob/a77c71efc5c2d75d3792235fda4dde3ba9748702/happybase/table.py#L22
[2]: https://github.com/wbolster/happybase/blob/a77c71efc5c2d75d3792235fda4dde3ba9748702/happybase/table.py#L28
[3]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/6563cb7096ded06a638dcb277bc4baca42333bd3/gcloud/bigtable/happybase/table.py#L68
[4]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/6563cb7096ded06a638dcb277bc4baca42333bd3/gcloud/bigtable/happybase/table.py#L92

**Comment by wbolster** [comment]
well, i am the author and i assure you that api is _not_ public. regardless of its name. these functions serve _no_ use to the end user of the library.

to clear up your misunderstanding: the public api is even more limited. the whole `happybase.table` module is _not_ public, nor are any of its sibling modules. the only public api is the one described in the documentation, and it's exported/imported from the main `happybase` package. anything that uses `happybase.submodule.something` is poking into internals, and that should not be done, even though we're consenting adults.

**Comment by dhermes** [comment]
Gotcha. I didn't realize. I'd suggest renaming those modules with an `_` to make that clear / be in line with Python convention.

**Comment by rimey** [comment]
I'm not sure how common it is to add a leading underscore to the names of private modules in the wider Python world.

**Comment by dhermes** [comment]
Having a leading underscore is the "definition" of non-public. Maybe I'm crazy?

**Comment by wbolster** [comment]
There is no single definition of what consitutes private/public in Python.

In general, for more established and matured projects, documented API and documented usage patterns (e.g. this class is public API, but instantiation should only happen through this other class) constitutes the public API, and everything else is not. Naming conventions and things like `__all__` surely help here, but those are never leading and often insufficient anyway to express the intentions of the author/maintainer.
