### ISSUE TITLE
Support custom encryption keys

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1841]
Can we support custom encryption keys for files uploaded?

Spec is here: https://cloud.google.com/compute/docs/disks/customer-supplied-encryption#top_of_page

**Comment by daspecster** [comment]
I think this might also be relevant.
https://cloud.google.com/storage/docs/encryption

**Comment by daspecster** [comment]
@dhermes @tseaver any thoughts on how we should pass the key and hash?

    bucket = client.create_bucket('my-bucket', key=key)

Then I think we can just hash the key.

    bucket = client.get_bucket('my-bucket', key=key)

This is the python they have to help you generate the key and hash.
```python
python -c 'import base64; import hashlib; import os; key = os.urandom(32); \
    print "Key: %sSHA256 hash: %s" % (base64.encodestring(key), \
    base64.encodestring(hashlib.sha256(key).digest()))'
```

https://cloud.google.com/storage/docs/encryption#customer-supplied

**Comment by daspecster** [comment]
@jgeewax, @stephenplusplus mentioned being able to just supply a password when storing data.
I think that would be very useful, but it's counter to the other documentation. I'm game for doing that and trying to be really clear in our docs on how to use it.

I'll continue in the direction of providing a password unless someone says otherwise.

**Comment by jgeewax** [comment]
Yea, the goal here is to be able to provide a key every time you upload a file.

In real life, people will probably want a key-derivation library to use for this, but to start this is just "hey, I'm uploading a file... here's the key to encrypt it with..."
