### ISSUE TITLE
Find a better caption for snippet in JSON docs generator.

### ISSUE THREAD

**Issue by daspecster** [GoogleCloudPlatform/gcloud-python#1984]
Right now the tag label is being used for the example caption. So you get example captions that look like "get_object" and "save_row_to_table".

It would be nice to have more human readable captions.

See: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1775#issuecomment-232704123

**Comment by tseaver** [comment]
Rather than snarfing the `docs/foo_snippets.py` file, could this be done by pulling in the `docs/foo_usage.rst` file, or maybe the HTML rendered from it by Sphinx?  The usage docs already have the "human-oriented" descriptions of the snippets, and presents them in a logical order, grouped into sections.

**Comment by daspecster** [comment]
For the site framework, there are only two fields for examples.
`example = {
    'caption': '',
    'code': ''
}`

I could parse the RST in this case I think. Docutils doesn't know what the `literalinclude` directive is though. So I would probably just manually parse it. I'll give it a go.

**Comment by daspecster** [comment]
http://daspecster.github.io/gcloud-python/#/docs/master/gcloud/pubsub

Update pushed to #1775.

**Comment by tseaver** [comment]
I would say that the implementation in #1775 is adequate for now.  We can look at a better rst -> markdown story for the usage / narrative docs later.
