### ISSUE TITLE
Add documentation about installing python-dev for Crypto (and any other C extension)

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#382]
See #67 for context

**Comment by dhermes** [comment]
@tseaver @jgeewax As mentioned in #67 this is a packaging / community problem.

**Comment by jgeewax** [comment]
I agree that it's a community issue. We still should have some documentation (or at least a link to a stack overflow question) about what to do when you run into a problem... This bug was just to add docs saying "install these packages". 

I'm fine leaving this closed given the suggestions in the installation section (top of http://googlecloudplatform.github.io/gcloud-python/index.html).

**Comment by dhermes** [comment]
Thanks
