### ISSUE TITLE
Add async methods

### ISSUE THREAD

**Issue by crhym3** [GoogleCloudPlatform/gcloud-python#40]
Is there a way to run multiple requests in parallel?
It would be really nice to be able to execute requests asynchronously, e.g. 
```
future = Query('MyKind').fetch_async()
result = future.get_result()
```
[NDB][1] has a great support for async operations using an event loop.

Is it something you guys might consider for future versions of the client?

[1]: https://developers.google.com/appengine/docs/python/ndb/async

**Comment by dhermes** [comment]
I'm closing this and folding into #557

**Comment by mikelambert** [comment]
I don't understand, why are you tying these (sync=datastore, async=ndb) together?

NDB has much more than an async API. I've traditionally used NDB synchronously, mainly for its ORM and memcaching.

The `datastore` sync API, meant it was unfortunately difficult to migrate this query:
```
CityTable.query(CityTable.city.IN(city_names)).fetch(100)
````

Because it would need to be rewritten as this (slower) serialized operation:
```
results = []
for city in city_names:
  q = client.query(kind='CityTable')
  q.add_filter('city', '=', city)
  results.extend(q.fetch(100))
```

Are you suggesting that NDB (along with the baggage of its ORM, memcaching-that-doesnt-work-outside-GAE, and sometimes-problematic eventloop) will be the only way to perform these parallelized lookups?
