### ISSUE TITLE
Batch (and Transaction) dataset_id should match that of Key / Query objects when added

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#447]
Proposed fix:

Do not ask for `dataset_id` in the constructor and instead gather it from the keys and queries used in the transaction.

This may require implementing #495 and **will** require removing the `self.begin()` [call][1] from `Transaction.__enter__`. (Can't begin until a query or entity is encountered.)

**Title** was: "Transaction does not rollback correctly when multiple datasets involved"

---

Witness the following code:

```python
>>> from gcloud import datastore
>>> cnxn = datastore.get_connection()
>>> dataset1 = cnxn.dataset('PROJ1')
>>> dataset2 = cnxn.dataset('PROJ2')
>>> e1 = dataset1.entity('foo')
>>> e2 = dataset2.entity('foo')
>>> e1['bar'] = e2['bar'] = 0
>>> e1.save()
<Entity[{'kind': u'foo', 'id': 5686683802533888L}] {'bar': 0}>
>>> e2.save()
<Entity[{'kind': u'foo', 'id': 5659313586569216L}] {'bar': 0}>
>>> with dataset1.transaction():
...     e1.delete()
...     e2.delete()
... 
>>> e1_still = dataset1.get_entity(e1.key())
>>> e1_still is None
True
>>> e2_still = dataset2.get_entity(e2.key())
>>> e2_still
<Entity[{'kind': u'foo', 'id': 5659313586569216L}] {u'bar': 0L}>
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/8faba35a266cd6280f125adf6035f902a07a26e4/gcloud/datastore/transaction.py#L246

**Comment by tseaver** [comment]
Note that calling `beginTransaction` requires the dataset ID (we can't do the RPC without it).  We already mad the dataset ID optional, falling back to the implicit one, but we cannot possibly rely on the keys, because we don't know them yet when we start the transaction.

I think it would be reasonable to say that users who don't want to use the implicit dataset ID know that when they create the batch / transaction, and can easily pass it.  We would then change the code in `put` / `delete` to reject *any* key not matching the one set in `__init__`.

**Comment by dhermes** [comment]
Yes I also came to this conclusion. Implicit saves us.

This re-opens the question about reading the dataset ID from every single key via [`_get_dataset_id_from_keys`][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/https://github.com/GoogleCloudPlatform/gcloud-python/commit/64aaed4190ca4b0b9457105636d0ec6893e824ca/gcloud/datastore/api.py#L63

**Comment by dhermes** [comment]
@tseaver I renamed to reflect the change.

Do you want to tackle this or should I?

**Comment by tseaver** [comment]
I'll take it.
