### ISSUE TITLE
DISCUSSION: Enforce user-friendly data in datastore

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#532]
This is two-fold:

1. Keep users from doing things which are allowed but may come back to bite them. For example, spaces in field names, negative dataset IDs

1. Document code paths which are allowed by our library but will fail on the backend. (Discussions in #329, #443, #529, #579, #616 and #620 need to be incorporated).

Is it better to add lots of conditionals and (IMO brittle) validity checks? Or, is the pragmatic approach (less code, let backend indicate failure) better?

/cc @jgeewax

**Comment by tseaver** [comment]
We should probably document the two kinds of cases (stuff the backend would allow, but which can't be spelled with our APIs, and stuff which our APIs would allow, but which the backend will reject) in a single place.

**Comment by jgeewax** [comment]
I personally like the idea of letting the back-end tell us when stuff is broken rather than lots of client-side validity checks. However I would like to make our stance clear on how we deal with bugs like ".filter() doesnt let me filter on properties that start with spaces" (in that case, I think our reply should be: "we're not going to change our API to support that disastrous edge case").

Is this ticket a good place to collect the list of things?

**Comment by dhermes** [comment]
@jgeewax This is a good place to collect.

RE: `.filter()`, as of #430, this is not something we need to actively worry about, though we could discourage the use of spaces by checking the property name. I am (moderately) against unnecessary branching (but aware Python is slow anyway).

**Comment by jgeewax** [comment]
I think we may have done everything we can do here... Thoughts?

**Comment by dhermes** [comment]
Well we haven't document anything and there are at least 6 bugs which ended up referring to this issue due to user confusion with the backend (i.e. rejecting an `Entity` that was indexed, they can never be).
