### ISSUE TITLE
Pin the "getting started with gcloud" snippet at the top of every page

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#553]
We do this on gcloud-node and it's *awesome* (http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.12.0/datastore/transaction)

Can we make this happen on the docs for gcloud-python too ?

**Comment by silvolu** [comment]
The reasons why the 'Getting Started' is not pinned in python is that we have the demos, so when I did the docs I decided to pin the 'API x in 10 seconds' sections to the top level module (datastore and storage), because they are more specific to each API.
To avoid having too much pinning going around, I avoided adding the 'Getting Started' as well.

**Comment by jgeewax** [comment]
Ah - I see this on http://googlecloudplatform.github.io/gcloud-python/storage-api.html

Can we pin it to the sub-sections? ie http://googlecloudplatform.github.io/gcloud-python/storage-buckets.html ?

**Comment by silvolu** [comment]
We can pin it to the sub-sections, but do you still want the 'Getting Started' as well? If not, I guess we should close #554.

**Comment by dhermes** [comment]
Looks like the fix (#554) got vetoed, closing this out.
