### ISSUE TITLE
Silent error when calling datastore.put() on nonlist

### ISSUE THREAD

**Issue by elibixby** [GoogleCloudPlatform/gcloud-python#649]
Repro instructions:

```
ent = datastore.Entity(key=datastore.Key('test',1))
datastore.put(ent)
```

Entity is not put in the datastore, and call completes successfully.

**Comment by dhermes** [comment]
@elibixby Thanks for reporting, this is bad! The entity is False-y, hence [nothing][1] is added to the batch.

By using a non-empty entity, the type mismatch actually causes an error (which is a "positive" in some sense):

```python
>>> ent['foo'] = 10
>>> datastore.put(ent)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/datastore/api.py", line 257, in put
    dataset_id = _require_dataset_id(dataset_id, entities[0].key)
KeyError: 0
```

----

**PROPOSED FIX**: Define `__bool__` and `__nonzero__` on the class so that `Entity` objects are never False-y.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/8e68a20cce2306f055557362b0c4a34909a36d1e/gcloud/datastore/api.py#L253-L254

**Comment by tseaver** [comment]
Changing `__bool__` / `__nonzero__` would break the "dict-ness" of Entity.  #677 adds a guard for that case, raising a ValueError.

**Comment by dhermes** [comment]
Yeah that occurred to me after writing. Fix looks good.
