### ISSUE TITLE
Add a short explanation of Batches vs Transactions ?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#711]
I think it'd be pretty useful to explain what the difference is between these two... doesn't need to be long, but something explaining when to use each, with links off to the datastore API documentation explaining in more detail.

**Comment by dhermes** [comment]
`Batches` can safely be used never by a user. `Transaction` maps to a [concept][1] outside of our library. I think a simpler solution could be just to put the `Batches` section below the fold somehow. WDYT?

A `Batch` powers `get() / put() / delete()` under the covers and it turns out most of the features needed to do this are needed for a `Transaction` (essentially everything except making the `begin_transaction` request and sending the transaction ID in the request),

[1]: https://cloud.google.com/datastore/docs/concepts/transactions

**Comment by jgeewax** [comment]
OK so you're saying we don't ever have a good reason to use a Batch by itself? If so, should we remove it's page from the docs?

**Comment by tseaver** [comment]
@jgeewax the point of `Batch` is to allow the developer to control the number of API requests, without the overhead / semantics of a transaction.  E.g., this generates only one request, without a transaction being created / finished:

```python
with datastore.Batch(connection) as batch:
    batch.put([entity1, entity2]
    batch.delete([key3, key4]
```

This might be a "power user" feature, but it should be documented.

**Comment by dhermes** [comment]
I think we can close this out. @jgeewax Feel free to re-open if you still think its an issue. Otherwise our practice of "autodoc" the things will be the standard.

Aside: We put `connection` module autodocs in the same file as `client` modules since users don't likely need to know about `connection` stuff. We could put `Batch` with `Transaction` if it were really an issue.
