### ISSUE TITLE
docs: transaction doesn't have property succeeded

### ISSUE THREAD

**Issue by pdknsk** [GoogleCloudPlatform/gcloud-python#781]
The docs still mention the ```succeeded``` property on transactions run with ```with``` even though it has been removed in ed0762b9531bc68f7a9e90835a0f0fbb75ddf383. It's not clear to me how to check for a successful transaction now. I suspect it throws an exception otherwise, which mirrors ```ndb``` behaviour, but I still check for ```_status == 3``` just in case.

**Comment by dhermes** [comment]
@pdknsk Thanks for pointing it out. I was hoping it was in an old docs build, but I confirmed it is [present][2] in `HEAD`.

----

As for how you can check it going forward, see my [comment][1] in the PR.

The context manager doesn't swallow exceptions. So `__exit__`ing the context manager without a failure is equivalent to `success`.

The only reason we kept the `_status` around is so that a `Transaction` object is "tombstoned" after one use. In other words, so people can't mistakenly try to re-enter a transaction.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/595#issuecomment-73312546
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/65341aebbfe8f03ce0b907061bce796ebbfb7f00/gcloud/datastore/transaction.py#L73-L88

**Comment by dhermes** [comment]
@pdknsk I'm going to close this when #784 is merged, let me know if you want to keep this open for some reason.
